-- MySQL Script generated by MySQL Workbench
-- Thu Jun  8 09:48:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`section`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`section` (
  `id_section` INT NOT NULL AUTO_INCREMENT,
  `name_section` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_section`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `id_question` INT NOT NULL AUTO_INCREMENT,
  `id_section` INT NOT NULL,
  `text_question` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id_question`),
  
  CONSTRAINT FK_id_section
    FOREIGN KEY (`id_section`)
    REFERENCES `mydb`.`section` (`id_section`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`options` (
  `option_id` INT NOT NULL AUTO_INCREMENT,
  `option_text` VARCHAR(85) NOT NULL,
  `obligatory` BIT NOT NULL,
  PRIMARY KEY (`option_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answer` (
  `id_answer` INT NOT NULL AUTO_INCREMENT,
  `valor_answer` INT NOT NULL,
  `id_question` INT NOT NULL,
  `options_option_id` INT NOT NULL,
  PRIMARY KEY (`id_answer`, `options_option_id`),

  CONSTRAINT fk_id_question
    FOREIGN KEY (`id_question`)
    REFERENCES `mydb`.`question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_answer_options1
    FOREIGN KEY (`options_option_id`)
    REFERENCES `mydb`.`options` (`option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question_has_options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question_has_options` (
  `question_id_question` INT NOT NULL,
  `options_option_id` INT NOT NULL,
  PRIMARY KEY (`question_id_question`, `options_option_id`),

  CONSTRAINT fk_question_has_options_question1
    FOREIGN KEY (`question_id_question`)
    REFERENCES `mydb`.`question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_question_has_options_options1
    FOREIGN KEY (`options_option_id`)
    REFERENCES `mydb`.`options` (`option_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
